#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &


# bspc functions
bspc monitor -d I II III IV

bspc config border_width         0


bspc config window_gap          10

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# stuff
~/.config/polybar/launch.sh

picom &

dunst &

feh --bg-scale ~/Pictures/wallpapers/twilight.jpg


[ "$1" = 0 ] && {
    xsetroot -cursor_name left_ptr &
}
